In [49]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [50]:
def get_data(URL):
    r = requests.get(URL) # wyslanie requesta
    content = r.content.decode('utf-8') # dekodowanie bitow do tekstu
    soup = BeautifulSoup(r.text, 'html') #utworzenie obiektu soup
    results = soup.find_all('section', {'class': 'ooa-1rnjex3 ev7e6t817'}) # wyszukanie znacznikow ktore przchowuja tytuly
    car_list = []
    for item in results:
        car = {
            'name': item.find('h1', {'class': 'ev7e6t89 ooa-1xvnx1e er34gjf0'}).text,
            'price': item.find('h3', {'class': 'ev7e6t82 ooa-bz4efo er34gjf0'}).text.replace(' ','').strip(),
            'mileage': item.find('dd', {'data-parameter': 'mileage'}).text.replace('km', '').replace(' ','').strip(),
            'fuel_type': item.find('dd', {'data-parameter': 'fuel_type'}).text,
            'gearbox': item.find('dd', {'data-parameter': 'gearbox'}).text,
            'year': item.find('dd', {'data-parameter': 'year'}).text,
            'location': item.find('p', {'class': 'ooa-gmxnzj'}).text,
            # 'link': item.find('h1', {'class': 'ev7e6t89 ooa-1xvnx1e er34gjf0'})['href'],
            }
        car_list.append(car)
        
    return car_list

In [51]:
def main():
    wszystkie_tytuly = []
    for page in range(1, 24): 
        URL = f'https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page={page}/'
        print('Pobieranie danych ze strony: ', URL)
        tytuly_ze_strony = get_data(URL)
        wszystkie_tytuly.extend(tytuly_ze_strony)
    global df
    df = pd.DataFrame(wszystkie_tytuly)
    df.to_csv(r'C:\Users\artur\Documents\Projects\scrapowanie-nauka\CSV\Scraping_otomoto2.csv', index = False)

In [52]:
if __name__ == "__main__":
    main()

Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=1/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=2/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=3/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=4/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=5/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=6/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=7/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=8/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=9/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=10/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=11/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=12/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=13/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=14/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=15/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=16/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=17/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=18/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=19/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=20/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=21/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=22/
Pobieranie danych ze strony:  https://www.otomoto.pl/osobowe/lodzkie?search%5Bfilter_enum_damaged%5D=0&search%5Bfilter_float_price%3Ato%5D=10000&page=23/

In [53]:
df

,name,price,mileage,fuel_type,gearbox,year,localization
0,Renault Megane,9500,277543,Benzyna+LPG,Manualna,2006,Stanisławów Drugi (Łódzkie)
1,Ford Focus C-Max 2.0 TDCi Platinium X,8432,270362,Diesel,Manualna,2005,Łódź (Łódzkie)
2,Volkswagen Polo 1.2 12V Trendline,8500,135000,Benzyna,Manualna,2007,Łódź (Łódzkie)
3,Peugeot 407 SW HDi 110 Blue Lion Business Line,8300,254000,Diesel,Manualna,2008,Paprotnia (Łódzkie)
4,Renault Scenic 1.9 dCi Exception,9900,147000,Diesel,Manualna,2003,Łask (Łódzkie)
...,...,...,...,...,...,...,...
705,Renault Laguna II 1.9 dCi Authentique,2400,293750,Diesel,Manualna,2002,Pożdżenice (Łódzkie)
706,Fiat Panda,8900,122000,Benzyna,Manualna,2007,Łódź (Łódzkie)
707,Kia Ceed 2.0 crdi Optimum,8250,289000,Diesel,Manualna,2007,Łódź (Łódzkie)
708,Ford Fusion 1.4 Trend,9200,241400,Benzyna,Manualna,2005,Pabianice (Łódzkie)
709,Volkswagen Golf,6000,300000,Benzyna,Manualna,1992,Tomaszów Mazowiecki (Łódzkie)